car_1 = "Бензин 2,5 (171 к.с.) 4х2 АКП (CVT)"
car_2 = "Бензин 2,5 (171 к.с.) 4х4 АКП (CVT) (INTENSE)"
Price = "29 486"
car1 = {
    "Price": "1 263 400",
    "Rear LED lights with dynamic turn indicators": "False",
    "external design": [
        "Layers on the roof",
        "Protective cover on the bumper",
        "Additional tinting of rear windows",
        "Alloy wheels 2-color 18'' new design with diamond grinding",
        "Metallic paint",
    ],
    "Panoramic glass roof": [],
    "interior design elements": [
        "Dark execution of the interior",
        "Combined fabric/eco leather seat upholstery in black",
        "Leather steering wheel",
        "Comfortable LED interior lighting",
    ],
    "multimedia": [
        "R-Link2 multimedia system with a 7'' touch LCD display (without navigation)",
        " 2 USB",
        "iPod dock",
        "jack",
        "3D Sound Arkamys audio system",
        "8 speakers",
        "support for Apple Car Play and Android ™ applications",
        "support for Android ™ applications Auto",
    ],
    "guarantee": [
        "3 years or 100,000 km",
        "Extended warranty of 4 years or 150,000 km ⁵",
    ],
    "management": [
        "Gear shift indicator",
        "ECOMODE function",
    ],
    "comfort": [
        "Front seats with mechanical length and height adjustment",
        "Rear seats with adjustable backrest angle",
        "central armrest with 2 cup holders",
        "Central sliding armrest",
        "2 cup holders with cooling and heating",
        "Heated front seats",
        "Heated rear side seats",
        "Windshield heating (including the area of the wiper blades)",
        "Rear window heating",
        "Two-zone climate control",
        "Air ducts for rear passengers",
        "Front power windows, impulse from the driver's side",
        "Front and rear electric windows",
        "External mirrors with heating, the function of electric adjustment and automatic folding",
        "Rearview mirror with electrochromic coating",
        "Illuminated make-up mirrors",
        'Key card "Free hands"',
        "On-board computer with the ability to configure and choose the color of the backlight",
        "3 12V sockets (front, on the central console behind, in the luggage compartment)",
        "Electric drive for opening and closing the trunk (front/four-wheel drive)",
    ],
    "safety": [
        "ESP (course stability system) + HSA (hill start assist system)",
        "AFU (emergency braking assistance system)",
        "ABS (anti-lock braking system)",
        "Tire pressure control",
        "Cruise control",
        "Front airbags",
        "Front and rear safety curtains",
        "Detachable front passenger airbag",
        "Front seat belts with height adjustment",
        "Rear 3-point seat belts",
        "Reminder about unfastened seat belts (passengers in the front and rear seats)",
        "Front headrests adjustable in height and tilt",
        "Headrests of the rear row of seats of the covering type, adjustable in height",
        "Central castle",
        "Attachment for ISOFIX child seat",
        "Lateral repeaters of turns",
        "Rear brake light (9 LEDs)",
        "Full LED headlights",
        "Designer LED daytime running lights",
        "Rear LED lights",
        "Dust protection",
        "Protection from dirt",
        "Protective shields for brake discs",
        "All-season tires",
        "Full size spare wheel",
        "Road safety kit",
        "Rain and light sensors",
        "Immobilizer",
        "Front and rear parking sensors",
        "Rear view camera",
        "Blind spot control system",
        "Driver fatigue control",
    ]
}
car2 = {
    "Price": "1 470 800",
    "Rear LED lights with dynamic turn indicators": "True",
    "external design": [
        "Layers on the roof",
        "Protective cover on the bumper",
        "Additional tinting of rear windows",
        "Alloy wheels 2-color 18'' new design with diamond grinding",
        "Metallic paint",
        'Special paint "black amethyst"'
    ],
    "Panoramic glass roof": [
        "with a hatch in the front of the car",
        "with a curtain with an electric drive",
        Price,
    ],
    "interior design elements": [
        "Dark execution of the interior",
        "Combined fabric/eco leather seat upholstery in black",
        "Leather steering wheel",
        "Comfortable LED interior lighting",
        "Black leather seats",
        "Leather seat upholstery NAPPA - black color",
        "Comfortable LED interior lighting (rear door)",
    ],
    "multimedia": [
        "Multimedia system R-Link2 with touch screen LCD 8.7",
        "navigation, 2 USB, iPod socket, jack,memory card slot",
        "3D Sound Arkamys audio system, 8 speakers; support for Apple Car applications Play and Android ™ Auto**",
        "Apple Car Play and Android ™ Auto app support**",
        "Bose premium audio system, 12 speakers + subwoofer",
    ],
    "guarantee": [
        "3 years or 100,000 km",
        "Extended warranty of 4 years or 150,000 km ⁵",
    ],
    "management": [
        "Gear shift indicator",
        "ECOMODE function",
    ],
    "comfort": [
        "Driver's seat with electric adjustment in length, height, in the waist",
        "front passenger seat with manual length and height adjustment",
        "Driver's seat with electric adjustment in length, height, manual waist adjustment",
        "front passenger seat with manual length and height adjustment",
        """"Comfort" package: Ventilated driver's seat with electric adjustment in length, height, in
        waist (with memory function); with massage function and adjustable pillow length
        seat; ventilated front passenger seat with electric length adjustment and
        height and adjustable pillow length + Front headrests of increased comfort +
        automatic folding of exterior mirrors with memory function + 2 12V sockets (front, in
        luggage compartment) //Ordered together with 'NAPPA Leather Seat Upholstery'""",
        """"Comfort" package: Ventilated driver's seat with electric adjustment in length, height, in
        waist (with memory function); with adjustable seat cushion length;
        ventilated front passenger seat with electric length and height adjustment and
        adjustable pillow lengthand + Front headrests of increased comfort + automatic
        assembly of exterior mirrors with memory function + 2 12V sockets (in the front, in the luggage compartment
        department) //Ordered together with 'NAPPA Leather Seat Upholstery'""",
        "Rear seats with adjustable backrest angle + central armrest with 2 cup holders",
        '"EasyBreak" system',
        "central armrest with 2 cup holders",
        "Central sliding armrest",
        "2 cup holders with cooling and heating",
        "Heated front seats",
        "Heated rear side seats",
        "Windshield heating (including the area of the wiper blades)",
        "Rear window heating",
        "Two-zone climate control",
        "Air ducts for rear passengers",
        "Front power windows, impulse from the driver's side",
        "Front and rear electric windows",
        "External mirrors with heating, the function of electric adjustment and automatic folding",
        "Rearview mirror with electrochromic coating",
        "Illuminated make-up mirrors",
        'Key card "Free hands"',
        "On-board computer with the ability to configure and choose the color of the backlight",
        "3 12V sockets (front, on the central console behind, in the luggage compartment)",
        "Electric drive for opening and closing the trunk (front/four-wheel drive)",
        "Heated rear side seats",
        "Heated steering wheel",
        "Headlight washer (works only when the headlights are on)",
    ],
    "safety": [
        "HDC (Descent Control System) (FWD/4WD)",
        "ESP (course stability system) + HSA (hill start assist system)",
        "AFU (emergency braking assistance system)",
        "ABS (anti-lock braking system)",
        "Tire pressure control",
        "Cruise control",
        "Front airbags",
        "Front and rear safety curtains",
        "Detachable front passenger airbag",
        "Front seat belts with height adjustment",
        "Rear 3-point seat belts",
        "Reminder about unfastened seat belts (passengers in the front and rear seats)",
        "Front headrests adjustable in height and tilt",
        "Headrests of the rear row of seats of the covering type, adjustable in height",
        "Central castle",
        "Attachment for ISOFIX child seat",
        "Lateral repeaters of turns",
        "Rear brake light (9 LEDs)",
        "Full LED headlights",
        "Designer LED daytime running lights",
        "Dust protection",
        "Protection from dirt",
        "Protective shields for brake discs",
        "All-season tires",
        "Full size spare wheel",
        "Road safety kit",
        "Rain and light sensors",
        "Immobilizer",
        "Front and rear parking sensors",
        "Rear view camera",
        "Blind spot control system",
        "Driver fatigue control",
        "Rear LED lights with dynamic turn indicators",
    ]
}
for an_element_of_external_design in car1["external design"]:
    print(an_element_of_external_design)
print(car2["Panoramic glass roof"][2])
